const $=id=>document.getElementById(id);
const fileInput=$("fileInput"),dropzone=$("dropzone"),resumeText=$("resumeText"),jobText=$("jobText");
const pool=["python","java","javascript","typescript","c","c++","sql","html","css","react","node","express","mongodb","mysql","postgresql","git","github","aws","azure","docker","kubernetes","power bi","tableau","excel","machine learning","deep learning","artificial intelligence","data science","data analytics","nlp","computer vision","tensorflow","pytorch","scikit-learn","rest api","api","figma","agile","scrum","linux"];
const verbs=["developed","built","created","designed","implemented","engineered","analyzed","optimized","automated","led","managed","improved","deployed","integrated","tested","delivered"];
const escapeReg=s=>s.replace(/[.*+?^$()|[\]\\]/g,"\\$&");
const has=(t,arr)=>arr.some(x=>new RegExp("\\b"+escapeReg(x)+"\\b","i").test(t));
function kws(job){const out=[];const l=job.toLowerCase();pool.forEach(k=>{if(l.includes(k))out.push(k)});return out.slice(0,35)}
async function handleFile(file){if(!file)return;$("fileName").textContent=file.name;try{const ext=file.name.toLowerCase().split(".").pop();if(ext==="txt"){resumeText.value=await file.text();return}if(ext==="docx"){const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});resumeText.value=r.value;return}if(ext==="pdf"){const pdfjs=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs";const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let out=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const c=await page.getTextContent();out.push(c.items.map(i=>i.str).join(" "))}resumeText.value=out.join("\n\n");return}throw Error("Unsupported file type")}catch(e){alert("Could not read the file. Paste the resume text instead.\n\n"+e.message)}}
fileInput.onchange=e=>handleFile(e.target.files[0]);["dragenter","dragover"].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.add("drag")}));["dragleave","drop"].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.remove("drag")}));dropzone.addEventListener("drop",e=>handleFile(e.dataTransfer.files[0]));
document.querySelectorAll("[data-job]").forEach(b=>b.onclick=()=>{jobText.value={software:"Software Developer\nRequirements: Java, Python, SQL, Git, REST API, OOP, data structures, algorithms, React, Node.js, teamwork.",data:"Data Scientist / AI Engineer\nRequirements: Python, SQL, machine learning, deep learning, pandas, scikit-learn, TensorFlow, statistics, NLP, Git.",web:"Full Stack Developer\nRequirements: JavaScript, TypeScript, React, Node.js, Express, MongoDB, REST API, HTML, CSS, GitHub, authentication."}[b.dataset.job]});
function words(s){return s.toLowerCase().match(/[a-z0-9+#.-]+/g)||[]}
function analyze(){const r0=resumeText.value.trim(),j0=jobText.value.trim();if(r0.length<80)return alert("Please upload or paste a resume first.");const r=r0.toLowerCase(),j=j0.toLowerCase(),all=kws(j0),matched=all.filter(k=>r.includes(k)),missing=all.filter(k=>!r.includes(k));const keywordScore=all.length?matched.length/all.length*100:70;
const sections=[["Contact",/@[^\s@]+\.[^\s@]+/.test(r)||r.includes("phone")],["Summary / Objective",has(r,["summary","objective","profile"])],["Education",has(r,["education","bachelor","b.tech","b.e.","degree"])],["Experience",has(r,["experience","internship","intern"])],["Skills",has(r,["skills","technical skills","technologies"])],["Projects",has(r,["projects","project"])],["Certifications",has(r,["certifications","certificates","certification"])]];
const contacts=[["Email",/@[^\s@]+\.[^\s@]+/.test(r)],["Phone",/(\+?\d[\d\s().-]{8,}\d)/.test(r)],["LinkedIn",r.includes("linkedin")],["GitHub",r.includes("github")]];
const wc=words(r).length, actionCount=verbs.filter(v=>r.includes(v)).length, sectionScore=sections.filter(x=>x[1]).length/7*100, contactScore=contacts.filter(x=>x[1]).length/4*100, actionScore=Math.min(100,actionCount/6*100), lengthScore=wc>=250&&wc<=900?100:wc<180?55:75, penalty=/(date of birth|father name|marital status|photo)/.test(r)?8:0;
const score=Math.max(0,Math.min(100,Math.round(keywordScore*.35+sectionScore*.2+contactScore*.15+actionScore*.15+lengthScore*.15-penalty)));render(score,matched,missing,sections,contacts,wc,actionCount)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function render(score,matched,missing,sections,contacts,wc,actionCount){$("results").classList.remove("hidden");$("score").textContent=score;$("ringValue").textContent=score+"%";$("scoreLabel").textContent=score>=80?"Strong ATS readiness":score>=65?"Good foundation — improve the gaps":"Needs optimization before applying";$("scoreRing").style.background="conic-gradient(var(--accent) "+score*3.6+"deg,#e9ebf2 0deg)";$("keywordStat").textContent=(matched.length+missing.length)?Math.round(matched.length/(matched.length+missing.length)*100)+"%":"N/A";$("sectionStat").textContent=sections.filter(x=>x[1]).length+"/7";$("contactStat").textContent=contacts.filter(x=>x[1]).length+"/4";$("wordStat").textContent=wc.toLocaleString();$("keywordCount").textContent=matched.length+" matched";$("keywordList").innerHTML=matched.map(k=>'<span class="keyword">✓ '+esc(k)+'</span>').join("")+missing.map(k=>'<span class="keyword missing">+ '+esc(k)+'</span>').join("");$("structureList").innerHTML=sections.map(x=>'<div class="check"><span>'+x[0]+'</span><b class="'+(x[1]?"yes":"no")+'">'+(x[1]?"Detected":"Missing")+'</b></div>').join("");
const issues=[];if(missing.length)issues.push(["⚠","Add relevant job keywords","Truthfully add useful terms from the job description where they match your actual skills. Missing: "+missing.slice(0,10).join(", ")+"."]);if(wc<250)issues.push(["↗","Add stronger evidence","Expand project or experience bullets with actions, technologies and measurable outcomes."]);if(wc>900)issues.push(["↘","Reduce repetition","Remove low-value or repetitive content and keep the most relevant evidence."]);if(!contacts.every(x=>x[1]))issues.push(["@","Complete contact links","Include a professional email, phone, LinkedIn and GitHub when relevant."]);if(!sections[1][1])issues.push(["✦","Add a targeted summary","Use 2–3 lines connecting your experience and skills to the target role."]);if(!sections[3][1])issues.push(["▣","Strengthen experience evidence","Include internships, freelance work, volunteering or substantial project experience."]);if(actionCount<4)issues.push(["✓","Use stronger action verbs","Start bullets with verbs such as built, implemented, optimized, automated, analyzed or deployed."]);if(/date of birth|father name|marital status|photo/.test(resumeText.value.toLowerCase()))issues.push(["!","Review personal details","Consider removing unnecessary personal details for most professional applications."]);$("issueCount").textContent=issues.length+" items";$("issues").innerHTML=issues.map(i=>'<div class="issue"><div>'+i[0]+'</div><div><strong>'+esc(i[1])+'</strong><p>'+esc(i[2])+'</p></div></div>').join("");$("structureLabel").textContent=sections.filter(x=>x[1]).length===7?"Complete":"Needs attention";$("extractedText").textContent=resumeText.value;window.scrollTo({top:$("results").offsetTop-20,behavior:"smooth"})}
$("analyzeBtn").onclick=analyze;$("copyBtn").onclick=async()=>{await navigator.clipboard.writeText($("extractedText").textContent);$("copyBtn").textContent="Copied!";setTimeout(()=>$("copyBtn").textContent="Copy",1200)};